#!/bin/bash

### Script to put our ssh key in remote hosts (short way, two words) for making life easier in new jobs :)
### This one could be an alias, but I've got plenty of them, so in a shellscript way works fine for me :) :)
### Also it could be a simple oneline, but I like to explain this kind of stuff to 'me in the future' :) :) :)

# Hostname definition
HOSTNAME="root@$1"

# ssh-copy-id installs an SSH key on a server as an authorized key.
sudo ssh-copy-id -i ~/.ssh/id_rsa.pub $HOSTNAME

### NOTES:
### Put it on a 'cool' location (a $PATH's one) to use it everywhere (as an alias)
### Usage: keys <servername>
